### ISSUE TITLE
Possible wrong class name being instantiated in Email handler

### ISSUE THREAD

**Issue by abychat** [iiretepii/Einstein-Email-Bot#2]
`Error  mdapiout/classes/EmailToCaseInboundHandler.cls  EmailToCaseInboundHandler  Invalid type: EmailObject
Error  mdapiout/classes/EmailToCaseInboundHandler.cls  EmailToCaseInboundHandler  Incompatible types since an instance of EmailObject is never an instance of Object

**Comment by iiretepii** [comment]
Fixed!
